실례지만 PR 하나만 올리겠습니다
ad-tado/2023-Effective-Java-Study pull request #1
Opened 2023-07-21 17:18 UTC by kchung1995

* .gitignore에 .idea, .ds_store 추가
* rootProject name이 죄다 똑같길래 제것만 수정

2023-07-23 04:28 UTC, NownS commented on kchung1995/settings.gradle.kts
> -rootProject.name = "effective"
저는그냥 제 모듈만 돌릴예정ㅋㅋ

2023-07-25 13:39 UTC, VSFe requested changes
시른데요

2023-07-30 06:27 UTC, kchung1995 commented
@VSFe
👀

2023-07-30 16:02 UTC, VSFe approved these changes

2023-07-30 16:06 UTC, VSFe requested changes
헉 PR 머지를 안 하시네

2023-07-30 16:10 UTC, merged