[Week 1] Item 01 - 03 PR
ad-tado/2023-Effective-Java-Study pull request #10
Opened 2023-07-31 10:52 UTC by kchung1995

enum class의 싱글톤 깨기 실패 테스트: 아무튼 못깸

2023-07-31 13:19 UTC, VSFe requested changes
LTGM

2023-08-05 08:58 UTC, sinclairr08 commented on kchung1995/src/test/java/org/adtado/katfun/effective/chapter02/item02/Item02JavaBeansResponseTest.java
> +        }
CountDownLatch를 통해 여러 스레드에서 setter 함수를 사용해도 문제가 없도록 한 코드네요.

저는 멀티스레드에서 자바 빈즈 패턴을 적용할 경우 문제가 생기는 코드를 구현했는데, 이런 방식으로 문제가 발생하지 않도록 막는 방법도 좋은 것 같습니다.

더불어 `ExecutorService`에 대해서도 몰랐는데 많이 배우고 갑니다 👍

2023-08-05 09:00 UTC, sinclairr08 approved these changes

2023-08-05 11:47 UTC, VSFe approved these changes
봐 줬 다 !

2023-08-05 11:47 UTC, merged